services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # queue
      - "15672:15672"  # admin dashboard
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
  
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: judge
      POSTGRES_PASSWORD: judge123
      POSTGRES_DB: judgedb